### ISSUE TITLE
Gamecrash in Mods-menu

### ISSUE THREAD

**Issue by Tzucaza** [Kalciphoz/kRPG#29]
What mods are needed to reproduce the bug:
KRPG (acticated)
some other mods so you can scroll inside the mods menu (where you activate mods). Only KRPG needs to be active for it to crash.
I put the list of all mods i have currently in the list down below, not sure if thats any use - no need to have any of them active

What happens:
when i scroll inside the mods-menu (where you acticate/disable mods) the game crashes.

Crash log:
[21:25:33] [1/INFO] [tML]: Starting tModLoader v0.11.6.2 Windows client (13.02.2020)
[21:25:33] [1/INFO] [tML]: Running on NetFramework 4.8
[21:25:33] [1/INFO] [tML]: Executable: E:\Steam\steamapps\common\Terraria\Terraria.exe
[21:25:33] [1/INFO] [tML]: Working Directory: E:\Steam\steamapps\common\Terraria
[21:25:33] [1/INFO] [tML]: Launch Parameters: 
[21:25:33] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:25:33] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:25:33] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:25:33] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[21:25:34] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[21:25:34] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[21:25:35] [1/DEBUG] [Terraria]: Graphics Device: NVIDIA GeForce GTX 1060 6GB {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[21:25:35] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[21:25:36] [1/INFO] [Terraria]: Loading Texture Pack: TexturePack.zip
[21:25:39] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 720, Height: 480, Fullscreen: False -> True, Display: \\.\DISPLAY1
[21:25:39] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 720 -> 1920, Height: 480 -> 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:25:45] [7/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[21:25:45] [7/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[21:25:45] [7/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:25:45] [7/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:25:46] [7/INFO] [Terraria]: JIT loading finished
[21:25:46] [8/INFO] [tML]: Unloading mods
[21:25:46] [8/INFO] [tML]: Finding Mods...
[21:25:47] [8/INFO] [tML]: Sandboxing: kRPG
[21:25:47] [8/INFO] [tML]: Instantiating Mods...
[21:25:47] [8/INFO] [tML]: Initializing: ModLoader v0.11.6.2
[21:25:47] [8/INFO] [tML]: Initializing: kRPG v2.0.5
[21:25:48] [8/INFO] [tML]: Setting up...
[21:25:48] [8/INFO] [tML]: Loading: ModLoader v0.11.6.2
[21:25:48] [8/INFO] [tML]: Loading: kRPG v2.0.5
[21:25:48] [8/INFO] [tML]: Adding Recipes...
[21:25:50] [1/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Player.GetModPlayer(Nullable`1 index)
   at Terraria.Player.GetModPlayer[T]()
   at kRPG.GameObjects.Items.kItem.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale) in kRPG\GameObjects\Items\kItem.cs:line 745
   at Terraria.ModLoader.ItemLoader.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item[] inv, Int32 context, Int32 slot, Vector2 position, Color lightColor)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item& inv, Int32 context, Vector2 position, Color lightColor)
   at Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw(Boolean justCheckingString, Vector2& size, SpriteBatch spriteBatch, Vector2 position, Color color, Single scale)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedString(SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Int32& hoveredSnippet, Single maxWidth, Boolean ignoreColors)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(SpriteBatch spriteBatch, DynamicSpriteFont font, String text, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Single maxWidth, Single spread)
   at Terraria.Utils.DrawBorderString(SpriteBatch sb, String text, Vector2 pos, Color color, Single scale, Single anchorx, Single anchory, Int32 maxCharactersDisplayed)
   at Terraria.GameContent.UI.Elements.UIText.DrawSelf(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIModItem.Draw(SpriteBatch spriteBatch)
   at Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIMods.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UserInterface.Draw(SpriteBatch spriteBatch, GameTime time)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[21:25:50] [1/ERROR] [Terraria]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Player.GetModPlayer(Nullable`1 index)
   at Terraria.Player.GetModPlayer[T]()
   at kRPG.GameObjects.Items.kItem.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale) in kRPG\GameObjects\Items\kItem.cs:line 745
   at Terraria.ModLoader.ItemLoader.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item[] inv, Int32 context, Int32 slot, Vector2 position, Color lightColor)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item& inv, Int32 context, Vector2 position, Color lightColor)
   at Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw(Boolean justCheckingString, Vector2& size, SpriteBatch spriteBatch, Vector2 position, Color color, Single scale)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedString(SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Int32& hoveredSnippet, Single maxWidth, Boolean ignoreColors)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(SpriteBatch spriteBatch, DynamicSpriteFont font, String text, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Single maxWidth, Single spread)
   at Terraria.Utils.DrawBorderString(SpriteBatch sb, String text, Vector2 pos, Color color, Single scale, Single anchorx, Single anchory, Int32 maxCharactersDisplayed)
   at Terraria.GameContent.UI.Elements.UIText.DrawSelf(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIModItem.Draw(SpriteBatch spriteBatch)
   at Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIMods.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UserInterface.Draw(SpriteBatch spriteBatch, GameTime time)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
[21:25:50] [1/FATAL] [Terraria]: Main engine crash
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Player.GetModPlayer(Nullable`1 index)
   at Terraria.Player.GetModPlayer[T]()
   at kRPG.GameObjects.Items.kItem.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale) in kRPG\GameObjects\Items\kItem.cs:line 745
   at Terraria.ModLoader.ItemLoader.PostDrawInInventory(Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, Single scale)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item[] inv, Int32 context, Int32 slot, Vector2 position, Color lightColor)
   at Terraria.UI.ItemSlot.Draw(SpriteBatch spriteBatch, Item& inv, Int32 context, Vector2 position, Color lightColor)
   at Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw(Boolean justCheckingString, Vector2& size, SpriteBatch spriteBatch, Vector2 position, Color color, Single scale)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedString(SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Int32& hoveredSnippet, Single maxWidth, Boolean ignoreColors)
   at Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(SpriteBatch spriteBatch, DynamicSpriteFont font, String text, Vector2 position, Color baseColor, Single rotation, Vector2 origin, Vector2 baseScale, Single maxWidth, Single spread)
   at Terraria.Utils.DrawBorderString(SpriteBatch sb, String text, Vector2 pos, Color color, Single scale, Single anchorx, Single anchory, Int32 maxCharactersDisplayed)
   at Terraria.GameContent.UI.Elements.UIText.DrawSelf(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIModItem.Draw(SpriteBatch spriteBatch)
   at Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.ModLoader.UI.UIMods.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UserInterface.Draw(SpriteBatch spriteBatch, GameTime time)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

**Comment by Tzucaza** [comment]
My list of mods (mostly/all inactive - needs cleaning):
KRPG
Boss Checklist
Even More Modifiers
Reduced Grinding
Various Weathers
Boss Corsor
Calamity Vanitys
Calamity Dimensions
Lumberjack NPC
Lightnung Essentials
Camping
No Angler Timer
Mounted Magic Mirror
Census
+100% increased Quality of Life
Artifical Altars
Corru and Crim NPCs
Which mod is this from?
Hard v1.0
Begone, Evil!
Dragon Ball terraria
Start with Base
Start with a starter bag
Lans no more banner
Lans auto join team
Mod helpers
GoodProLib - beta
Gensokyo
Fast extractinator
Fargos Mutant Mod
Everything deserves a Theme
Crystilium
Campfire Buffs
More accesories
Leveld compatibility patch Thorium
Yet another Boss health bar
Thorium
leveled mod
Alchemist NPC Lite
Wing Slot
WeaponOut lite
Very Short Respawn Time
Vein Miner
Spirit Mod
Reforge Armor
Recip Browser
Prefixes+
Portable Storage
Orchid Mineshaft
No More Tombs
More endless ammo
Max stack plus extra
Magic storage
Lans unlimited Buff slots
Lans shared map
Improved Pillar Event
Frash Start
Fluid Libary
Fishing 2.0
Container Libary
Calamity Mod Extra Music
Chads Furniture mod
Calamity Vanilla buff
Calamity mod Music
Calamity Mod (No Calamity Music)
Better Night sky
Better Multiplayer
Base Libary
Auto Trash
Auto Reforge
Colored Damage Types

**Comment by TNTftw21** [comment]
I can confirm I get this crash with far fewer mods. I have yet to narrow it down, though, as it's not even consistent. It crashed twice, and then when I went through to actually see where it crashed in the mod menu (kRPG was off-screen) it worked fine.

**Comment by FairfieldTekLLC** [comment]
Ok, it appears that you need to restart terraria after you enable new mods.  This is an API issue, not kRPG.
